### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by Jonato** [FXMisc/fxmisc.github.io#2]
KeyboardFX
de.jonato.keyboardfx
https://github.com/Jonato/KeyboardFX

Manage your KeyEvents and KevEvent combinations easily.

**Comment by TomasMikula** [comment]
Hi,

fxmisc.org is meant to help projects get to the maven repository with a package name `org.fxmisc.yourproject`. It seems you already publish your artifacts under `de.jonato.keyboardfx`, so there is nothing fxmisc.org can offer you, unless you want to change the package name and maven group to `org.fxmisc.keyboardfx`.

Regards,
Tomas
